#!/bin/zsh

checkstatuspull(){
  grep "nothing to commit, " /tmp/pullmost-status >/dev/null
  statusret=$?
  grep "Already up to date." /tmp/pullmost-pull >/dev/null

  if [[ $statusret == 0 && $? == 0 ]]; then
    return 0
  else
    return 1
  fi
}


# Try to pull a directory, and then print status.
# Does nothing if it is not a directory, or the directory is not git.
trypull(){
  if [ ! -d $1 ]; then
    return                  # Not even a dir.
  fi

  cd $1
  if [ -d .git ]; then
    git pull 2>/tmp/pullmost-pull >/tmp/pullmost-pull
    git status 2>/tmp/pullmost-status >/tmp/pullmost-status

    checkstatuspull

    if [[ $? == 0 ]];
    then
      tput setab 2
      echo -e "$1! \x1b[K"
      tput op
    else
      tput setab 1
      echo -e "$1: \x1b[K"
      tput op
      cat /tmp/pullmost-pull
      echo
      cat /tmp/pullmost-status
      echo
    fi

  fi
  cd ..
}


for i in *; do
  trypull $i
done
